image: danger89/gtk3-docker-cmake-ninja:2.1

variables:
  GIT_SUBMODULE_STRATEGY: recursive

static_code_analysis:
  script: ./check.sh

doxygen:
   #stage: analysis
   before_script:
     - mkdir -p build/docs
   script:
     - doxygen docs/Doxyfile
   artifacts:
     paths:
       - build/docs/html/

build:
  script: ./scripts/build_prod.sh
  artifacts:
    name: "Packages + Documentation"
    expire_in: 1 week
    paths:
    - build_prod/browser-*.deb
    - build_prod/browser-*.rpm
    - build_prod/browser-*.tar.gz
  cache:
      key: "$CI_PIPELINE_ID"
      paths:
        - build_prod/bin
      policy: push

