image: "danger89/cmake:latest"

static_code_analysis:
  script: ./check.sh

build:
  script: ./scripts/build_prod.sh
  artifacts:
    name: "Packages + Documentation"
    expire_in: 1 week
    paths:
    - doc/doxygen/
    - build_prod/WineGUI-*.deb
    - build_prod/WineGUI-*.rpm
    - build_prod/WineGUI-*.tar.gz
  cache:
      key: "$CI_PIPELINE_ID"
      paths:
        - build_prod/bin
      policy: push

