image: https://gitlab.melroy.org/DWWW/dependency_proxy/containers/danger89/qt-cmake:latest

static_code_analysis:
  script: ./check.sh

build:
  script: ./scripts/build_prod.sh
  artifacts:
    name: "Packages + Documentation"
    expire_in: 1 week
    paths:
    #- doc/doxygen/
    - build_prod/browser-*.deb
    - build_prod/browser-*.rpm
    - build_prod/browser-*.tar.gz
  cache:
      key: "$CI_PIPELINE_ID"
      paths:
        - build_prod/bin
      policy: push

